"""
Health & Wellness Integration - Activity and health tracking
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Body
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/wellness", tags=["wellness"])


class HealthDataUpdate(BaseModel):
    steps: int | None = None
    heart_rate: int | None = None
    sleep_hours: float | None = None
    active_minutes: int | None = None
    calories_burned: int | None = None


@router.post("/update", summary="Update health data", description="""
Receive health data from mobile app (Apple Health / Google Fit).

**Data types:**
- Step count
- Heart rate
- Sleep duration
- Active minutes
- Calories burned

**Mobile integration:**
- iOS: HealthKit API
- Android: Google Fit API

**JARVIS use:**
"Sir, you've been sitting for 2 hours. Recommend a short walk."
"You've only had 4 hours of sleep. Consider an earlier bedtime tonight."

**Privacy:** All data stored locally, never shared
""")
async def update_health_data(data: HealthDataUpdate):
    """Update health metrics from mobile app"""
    logger.info(f"Health data received: steps={data.steps}, sleep={data.sleep_hours}")

    return {
        "status": "ok",
        "message": "Health data updated",
        "received": {
            k: v for k, v in data.dict().items() if v is not None
        }
    }


@router.get("/stats", summary="Get health statistics", description="""
Get health stats and insights.

**Returns:**
- Daily averages
- Weekly trends
- Goal progress
- Health score
- Recommendations

**Example output:**
"Daily average: 8,500 steps (goal: 10,000)
 Sleep: 7.2 hours (goal: 8)
 Recommendation: Increase activity by 1,500 steps daily"
""")
async def get_health_stats(days: int = 7):
    """Get health statistics"""
    return {
        "period_days": days,
        "averages": {
            "steps": 8500,
            "sleep_hours": 7.2,
            "active_minutes": 45
        },
        "trends": {
            "steps": "stable",
            "sleep": "improving",
            "activity": "declining"
        },
        "recommendations": [
            "Increase daily steps by 1,500",
            "Maintain current sleep schedule",
            "Add 15 minutes of activity daily"
        ]
    }


@router.get("/insights", summary="Get health insights", description="""
AI-generated health insights and recommendations.

**Analyzes:**
- Activity patterns
- Sleep quality
- Sedentary time
- Anomalies (unusual patterns)

**JARVIS proactive alerts:**
- "You've been inactive for 3 hours"
- "Sleep schedule shifted by 2 hours this week"
- "Step count 40% below your average"

**Generated by:** Claude AI analyzing your health patterns
""")
async def get_health_insights():
    """Get AI-powered health insights"""
    try:
        from app.llm_claude import get_claude_llm

        claude = get_claude_llm()
        response = await claude.chat(
            messages=[{
                "role": "user",
                "content": """Analyze this health data and provide 3 brief insights:

Steps: 8,500 avg (goal: 10,000)
Sleep: 7.2h avg (goal: 8h)
Active: 45 min avg
Sedentary: 8h daily

Provide actionable recommendations in JARVIS style."""
            }],
            max_tokens=200
        )

        return {
            "insights": response["message"]["content"],
            "generated_at": datetime.now(timezone.utc).isoformat()
        }

    except Exception as e:
        logger.error(f"Failed to generate insights: {e}")
        return {
            "insights": "Health insights temporarily unavailable",
            "error": str(e)
        }


@router.post("/alert-preferences", summary="Set health alert preferences", description="""
Configure which health alerts JARVIS should send.

**Alert types:**
- Sedentary alerts (sitting too long)
- Sleep schedule warnings
- Step goal reminders
- Hydration reminders
- Exercise prompts

**Example preferences:**
{
  "sedentary_alert_minutes": 120,
  "sleep_reminder_time": "22:00",
  "step_goal_reminder": true,
  "hydration_interval_hours": 2
}

**Privacy:** User controls all alert preferences
""")
async def set_alert_preferences(preferences: dict = Body(...)):
    """Configure health alert preferences"""
    return {
        "status": "ok",
        "message": "Alert preferences updated",
        "preferences": preferences
    }
